### PR TITLE
Added option MSI auth for development in ADT Model Viewer

### PR DESCRIPTION
**Pull request by katriendg**
Added the option through app settings for choosing Managed Identity for development.
Also upgraded Nuget to ADT release SDK (from preview).

### CODE REVIEW

**Comment by SamVanhoutte** [comment]
Awesome, I was just looking for this as well.

**Comment by alinamstanciu** [comment]
Thanks @katriendg for this change, you can also add me as reviewer. I've looked at your changes, they look good to me.
I've poked Kevin to review this one. @khilscher , could you please review it?

**Review by alinamstanciu — APPROVED** [review]
LGTM, thanks Katrien!

**Review by khilscher — APPROVED** [review]
Looks good.

**Pull request merged**
